site_description: "ByteDesign - The ByteDesign Design System"
google_analytics:
root_domain: design.bytedance.net
vue_version: 2.5.16

# Algolia Search
algolia_search:
  enable: true
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"


cloud_sponsors:
  - url: http://cloud.youku.com/index.php?source=vuejs
    img: bytedance_cloud.png

uikit:
  - name: 国内主题 UiKit
    description: 面向国内产品的主题及组件模板
    version: V 0.1
    update: 2019.01.31
    img: sketch.png
    url: #
  - name: 国际化 i18n UiKit
    description: 面向海外产品的主题及组件模板
    version: V 0.1
    update: 2019.01.31
    img: xigua.png
    url: #
  - name: Axure Components
    description: 这里是描述内容
    version: V0.1
    update: 2019.01.31
    img: huoshan.png
    url: #
  - name: 图标库 ByteIcon
    description: 通用的图标库 Sketch Library
    version: V 0.1
    update: 2019.01.31
    img: xigua.png
    url: #
  - name: 图表库 ByteChart
    description: 数据可视化模板库 Sketch Library
    version: V0.1
    update: 2019.01.31
    img: huoshan.png
    url: #

products:
  - url: #
    img: douyin.svg
    name: 抖音短视频
  - url: #
    img: toutiao.svg
    name: 今日头条
  - url: #
    img: xigua.svg
    name: 西瓜视频
  - url: #
    img: huoshan.svg
    name: 火山小视频
  - url: #
    img: dcd.svg
    name: 懂车帝
  - url: #
    img: csj.svg
    name: 穿山甲
  - url: #
    img: bytedance.png
    name: 字节跳动
  - url: #
    img: oceanengine.gif
    name: 巨量引擎
  - url: #
    img: tiktok.png
    name: TikTok
  - url: #
    img: bv.png
    name: Buzz Video
  - url: #
    img: tb.png
    name: Top Buzz
  - url: #
    img: tiktok-ads.svg
    name: TikTok Ads
  - url: #
    img: chengzijianzhan.png
    name: 橙子建站
  - url: #
    img: xiaoliuim.png
    name: 小六客服
  - url: #
    img: crm.png
    name: 飞鱼 CRM
  - url: #
    img: xingtu.png
    name: 星图
  - url: #
    img: jihe.svg
    name: 即合
  - url: #
    img: dmp.png
    name: 云图 DMP
  - url: #
    img: cc.svg
    name: 创意中心
